const users = [
    {
        id: 1,
        first_name: "Devi",
        last_name: "Whale",
        email: "dwhale0@last.fm",
        catchphrase: "Synergized exuding firmware",
      },
      {
        id: 2,
        first_name: "Paxon",
        last_name: "Semechik",
        email: "psemechik1@gizmodo.com",
        catchphrase: "Intuitive national approach",
      },
      {
        id: 3,
        first_name: "Karin",
        last_name: "Turri",
        email: "kturri2@washington.edu",
        catchphrase: "User-centric multimedia collaboration",
      },
      {
        id: 4,
        first_name: "Barnabas",
        last_name: "Filpo",
        email: "bfilpo3@joomla.org",
        catchphrase: "Mandatory asymmetric synergy",
      },
      {
        id: 5,
        first_name: "Josselyn",
        last_name: "Greenless",
        email: "jgreenless4@blinklist.com",
        catchphrase: "Monitored bifurcated synergy",
      },
      {
        id: 6,
        first_name: "Saundra",
        last_name: "Piggen",
        email: "spiggen5@cloudflare.com",
        catchphrase: "Versatile well-modulated algorithm",
      },
      {
        id: 7,
        first_name: "Kally",
        last_name: "Allebone",
        email: "kallebone6@addthis.com",
        catchphrase: "Extended discrete project",
      },
      {
        id: 8,
        first_name: "Waldo",
        last_name: "Tanser",
        email: "wtanser7@acquirethisname.com",
        catchphrase: "Profound incremental functionalities",
      },
      {
        id: 9,
        first_name: "Elora",
        last_name: "Brissard",
        email: "ebrissard8@tinypic.com",
        catchphrase: "Team-oriented fresh-thinking customer loyalty",
      },
      {
        id: 10,
        first_name: "Cate",
        last_name: "Postians",
        email: "cpostians9@nhs.uk",
        catchphrase: "Ameliorated explicit hardware",
      },
      {
        id: 11,
        first_name: "Hallie",
        last_name: "Kemshell",
        email: "hkemshella@prweb.com",
        catchphrase: "Proactive didactic Graphic Interface",
      },
      {
        id: 12,
        first_name: "Carlo",
        last_name: "Pringell",
        email: "cpringellb@ask.com",
        catchphrase: "Fundamental real-time archive",
      },
      {
        id: 13,
        first_name: "Gib",
        last_name: "Ussher",
        email: "gussherc@linkedin.com",
        catchphrase: "Proactive systematic core",
      },
      {
        id: 14,
        first_name: "Sella",
        last_name: "Byfield",
        email: "sbyfieldd@businesswire.com",
        catchphrase: "Cross-platform homogeneous paradigm",
      },
      {
        id: 15,
        first_name: "Krispin",
        last_name: "Faircliff",
        email: "kfaircliffe@cafepress.com",
        catchphrase: "Profound motivating strategy",
      },
      {
        id: 16,
        first_name: "Pandora",
        last_name: "Bosence",
        email: "pbosencef@mit.edu",
        catchphrase: "Streamlined modular task-force",
      },
      {
        id: 17,
        first_name: "Felice",
        last_name: "Abram",
        email: "fabramg@ehow.com",
        catchphrase: "Ameliorated multimedia access",
      },
      {
        id: 18,
        first_name: "Celinka",
        last_name: "Muckart",
        email: "cmuckarth@newyorker.com",
        catchphrase: "Switchable interactive Graphic Interface",
      },
      {
        id: 19,
        first_name: "Vonni",
        last_name: "Cashley",
        email: "vcashleyi@marriott.com",
        catchphrase: "Networked neutral local area network",
      },
      {
        id: 20,
        first_name: "Deeann",
        last_name: "Huish",
        email: "dhuishj@photobucket.com",
        catchphrase: "Multi-channelled didactic circuit",
      }]

      export default users;